# Generated by Django 4.2.11 on 2024-06-09 13:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='createrd_at',
        ),
        migrations.AddField(
            model_name='member',
            name='department',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='gender',
            field=models.CharField(default='남성', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='studentID',
            field=models.CharField(default=2020000000, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='type',
            field=models.BooleanField(default=0),
        ),
    ]
