# Generated by Django 4.2.11 on 2024-06-09 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_member_createrd_at_member_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='notSchool',
            field=models.BooleanField(default=0),
        ),
    ]
