# Generated by Django 4.2.11 on 2024-06-09 14:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_member_notschool'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='createrd_at',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
