# Generated by Django 4.2.11 on 2024-06-09 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_member_createrd_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='createrd_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
