# Generated by Django 4.2.11 on 2024-06-10 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_member_createrd_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='over', to='main.member'),
        ),
    ]
